version: '3.8'
services:
api:
build: .
environment:
- NODE_ENV=production
- DATABASE_URL=postgresql://laptracker:laptracker123@db:5432/lap_tracker
- CORS_ORIGINS=http://localhost:8080
- ADMIN_TOKEN=change-me
ports:
- "3000:3000"
depends_on:
- db
restart: unless-stopped
db:
image: postgres:15-alpine
environment:
- POSTGRES_DB=lap_tracker
- POSTGRES_USER=laptracker
- POSTGRES_PASSWORD=laptracker123
volumes:
- postgres_data:/var/lib/postgresql/data
ports:
- "5432:5432"
restart: unless-stopped
volumes:
postgres_data:
